ALTER TABLE videos ADD COLUMN parent_video_id INT NULL DEFAULT NULL;
ALTER TABLE videos ADD COLUMN clip_start INT NULL DEFAULT NULL;
ALTER TABLE videos ADD COLUMN clip_end INT NULL DEFAULT NULL;
ALTER TABLE videos ADD COLUMN is_short TINYINT(1) NOT NULL DEFAULT 0;
